-- ==========================================================================
-- Langkah 12 - Data contoh
-- Dataset yang sama persis dengan yang dipakai lab di situs.
-- Dihasilkan oleh ORACLEDECK (node tools/gen_oracle.js) - jangan sunting manual.
-- ==========================================================================

SET DEFINE OFF;

-- pasien (12 baris)
INSERT ALL
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (1, 'Budi Santoso', 'Jl. Merdeka 12', 'L', 'Demam Berdarah', '081234567001', 'Jakarta')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (2, 'Siti Aminah', 'Jl. Kenanga 5', 'P', 'Tifus', '081234567002', 'Jakarta')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (3, 'Andi Wijaya', 'Jl. Melati 9', 'L', 'Asma', '081234567003', 'Bandung')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (4, 'Rina Marlina', 'Jl. Anggrek 21', 'P', 'Anemia', '081234567004', 'Bandung')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (5, 'Joko Susilo', 'Jl. Mawar 3', 'L', 'Diabetes', '081234567005', 'Surabaya')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (6, 'Dewi Lestari', 'Jl. Dahlia 7', 'P', 'Hipertensi', '081234567006', 'Surabaya')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (7, 'Agus Setiawan', 'Jl. Cempaka 14', 'L', 'Demam Berdarah', '081234567007', 'Jakarta')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (8, 'Nurul Hidayah', 'Jl. Flamboyan 2', 'P', 'Migrain', '081234567008', 'Bandung')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (9, 'Hendra Gunawan', 'Jl. Teratai 18', 'L', 'Patah Tulang', '081234567009', 'Surabaya')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (10, 'Maya Anggraini', 'Jl. Sakura 30', 'P', 'Tifus', '081234567010', 'Jakarta')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (11, 'Rudi Hartono', 'Jl. Kamboja 11', 'L', 'Asma', '081234567011', 'Bandung')
  INTO PASIEN (ID_PASIEN, NAMA_PASIEN, ALAMAT_PASIEN, JENIS_KELAMIN, PENYAKIT, NO_HP, KOTA) VALUES (12, 'Lina Wahyuni', 'Jl. Bougenville 6', 'P', 'Anemia', '081234567012', 'Surabaya')
SELECT * FROM dual;

-- dokter (6 baris)
INSERT ALL
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (1, 'dr. Surya Atmaja', 'Jl. Diponegoro 1', DATE '1975-04-12', '082100000001', 'Penyakit Dalam', 'Senin-Rabu', 'Jakarta')
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (2, 'dr. Anita Kusuma', 'Jl. Sudirman 44', DATE '1982-08-30', '082100000002', 'Anak', 'Selasa-Kamis', 'Jakarta')
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (3, 'dr. Bambang Riyadi', 'Jl. Asia Afrika 8', DATE '1969-01-05', '082100000003', 'Bedah', 'Rabu-Jumat', 'Bandung')
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (4, 'dr. Citra Dewanti', 'Jl. Braga 19', DATE '1988-11-21', '082100000004', 'Saraf', 'Senin-Kamis', 'Bandung')
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (5, 'dr. Eko Prabowo', 'Jl. Tunjungan 2', DATE '1979-06-17', '082100000005', 'Jantung', 'Selasa-Sabtu', 'Surabaya')
  INTO DOKTER (ID_DOKTER, NAMA_DOKTER, ALAMAT_DOKTER, TANGGAL_LAHIR, NO_HP, SPESIALIS, WAKTU_KERJA, KOTA) VALUES (6, 'dr. Farah Nadia', 'Jl. Pemuda 27', DATE '1985-02-09', '082100000006', 'Paru', 'Senin-Jumat', 'Surabaya')
SELECT * FROM dual;

-- administrator (4 baris)
INSERT ALL
  INTO ADMINISTRATOR (ID_ADMIN, NAMA_ADMIN, WAKTU_JAGA, KOTA) VALUES (1, 'Ratna Sari', 'Pagi', 'Jakarta')
  INTO ADMINISTRATOR (ID_ADMIN, NAMA_ADMIN, WAKTU_JAGA, KOTA) VALUES (2, 'Dimas Prakoso', 'Siang', 'Jakarta')
  INTO ADMINISTRATOR (ID_ADMIN, NAMA_ADMIN, WAKTU_JAGA, KOTA) VALUES (3, 'Yuni Astuti', 'Malam', 'Bandung')
  INTO ADMINISTRATOR (ID_ADMIN, NAMA_ADMIN, WAKTU_JAGA, KOTA) VALUES (4, 'Tono Saputra', 'Pagi', 'Surabaya')
SELECT * FROM dual;

-- pasien_dokter (14 baris)
INSERT ALL
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (1, 1, 1, DATE '2025-09-01', 'Paracetamol 500mg', 250000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (2, 1, 2, DATE '2025-09-02', 'Amoxicillin 500mg', 275000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (3, 2, 7, DATE '2025-09-02', 'Oralit + Vitamin', 180000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (4, 2, 10, DATE '2025-09-03', 'Ciprofloxacin', 320000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (5, 3, 3, DATE '2025-09-04', 'Salbutamol inhaler', 410000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (6, 4, 8, DATE '2025-09-04', 'Sumatriptan', 390000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (7, 3, 11, DATE '2025-09-05', 'Salbutamol inhaler', 410000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (8, 4, 4, DATE '2025-09-05', 'Sulfas ferrosus', 210000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (9, 5, 5, DATE '2025-09-08', 'Metformin 850mg', 450000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (10, 5, 6, DATE '2025-09-08', 'Amlodipin 10mg', 380000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (11, 6, 12, DATE '2025-09-09', 'Sulfas ferrosus', 215000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (12, 3, 9, DATE '2025-09-10', 'Gips + Analgesik', 850000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (13, 1, 1, DATE '2025-09-12', 'Kontrol - Paracetamol', 150000)
  INTO PASIEN_DOKTER (ID, ID_DOKTER, ID_PASIEN, WAKTU_PERIKSA, RESEP, BIAYA) VALUES (14, 5, 5, DATE '2025-09-15', 'Kontrol - Metformin', 175000)
SELECT * FROM dual;

-- dokter_admin (8 baris)
INSERT ALL
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (1, 1, 1)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (2, 2, 1)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (3, 1, 2)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (4, 2, 2)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (5, 3, 3)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (6, 4, 3)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (7, 5, 4)
  INTO DOKTER_ADMIN (ID_DATA, ID_DOKTER, ID_ADMIN) VALUES (8, 6, 4)
SELECT * FROM dual;

-- daftar (12 baris)
INSERT ALL
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (1, 1, 1, DATE '2025-09-01')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (2, 2, 1, DATE '2025-09-02')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (3, 7, 2, DATE '2025-09-02')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (4, 10, 2, DATE '2025-09-03')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (5, 3, 3, DATE '2025-09-04')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (6, 8, 3, DATE '2025-09-04')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (7, 11, 3, DATE '2025-09-05')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (8, 4, 3, DATE '2025-09-05')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (9, 5, 4, DATE '2025-09-08')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (10, 6, 4, DATE '2025-09-08')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (11, 12, 4, DATE '2025-09-09')
  INTO DAFTAR (ID_DAFTAR, ID_PASIEN, ID_ADMIN, TANGGAL_DAFTAR) VALUES (12, 9, 3, DATE '2025-09-10')
SELECT * FROM dual;

COMMIT;

-- Verifikasi jumlah baris:
SELECT 'pasien' AS tabel, COUNT(*) AS baris FROM PASIEN;
SELECT 'dokter' AS tabel, COUNT(*) AS baris FROM DOKTER;
SELECT 'administrator' AS tabel, COUNT(*) AS baris FROM ADMINISTRATOR;
SELECT 'pasien_dokter' AS tabel, COUNT(*) AS baris FROM PASIEN_DOKTER;
SELECT 'dokter_admin' AS tabel, COUNT(*) AS baris FROM DOKTER_ADMIN;
SELECT 'daftar' AS tabel, COUNT(*) AS baris FROM DAFTAR;
